import torch
from abc import ABC, abstractmethod


class EPLBase(ABC):
    """
    Base class for Enhanced Pseudo Labeling strategies.

    This class defines the interface that all EPL implementations must follow.
    It provides a framework for enhancing pseudo labels generated by source models
    before using them for target domain adaptation.
    """

    @abstractmethod
    def enhance(self,
                  *args,
                  **kwargs) -> torch.Tensor:
        pass
