import numpy as np
import torch
from abc import ABC, abstractmethod

from splae.models.epl.base import EPLBase
from splae.utils import one_hot, get_largest_component


class MorphEPL(EPLBase):
    """
    Base class for Enhanced Pseudo Labeling strategies.

    This class defines the interface that all EPL implementations must follow.
    It provides a framework for enhancing pseudo labels generated by source models
    before using them for target domain adaptation.
    """
    def __init__(self,
                 num_classes: int,
                 ignore_index = -1):
        self.num_classes = num_classes
        self.ignore_index = ignore_index

    def enhance(self,
                  logits: torch.Tensor,
                  original_pseudo_labels: torch.Tensor,
                  image: torch.Tensor = None,
                  **kwargs) -> torch.Tensor:
        """
        Enhance pseudo labels using the specific strategy.

        Args:
            logits: Model output logits of shape (B, C, H, W)
            original_pseudo_labels: Original pseudo labels of shape (B, H, W)
            **kwargs: Additional parameters for enhancement

        Returns:
            enhanced_pseudo_labels: Enhanced pseudo labels of shape (B, H, W)
        """
        one_hot_mask = one_hot(original_pseudo_labels, self.num_classes, self.ignore_index).squeeze(0).cpu().detach().numpy()
        largest_components = np.zeros_like(one_hot_mask)
        for cls_idx in range(self.num_classes):
            # Get the largest component per class
            largest_component = get_largest_component(one_hot_mask[cls_idx])
            largest_components[cls_idx] = largest_component
        largest_components = torch.from_numpy(largest_components).to(original_pseudo_labels.device)
        enhanced_pseudo_labels = torch.argmax(largest_components, dim=0).unsqueeze(0)
        return enhanced_pseudo_labels
